/* Generated By:JavaCC: Do not edit this line. MiniJajaTreeConstants.java Version 7.0.12 */
package fr.m1comp5.AST;

public interface MiniJajaTreeConstants
{
  public int JJTROOT = 0;
  public int JJTCLASSE = 1;
  public int JJTIDENT = 2;
  public int JJTVOID = 3;
  public int JJTVNIL = 4;
  public int JJTDECLS = 5;
  public int JJTCST = 6;
  public int JJTMETHODE = 7;
  public int JJTVARS = 8;
  public int JJTTABLEAU = 9;
  public int JJTVAR = 10;
  public int JJTOMEGA = 11;
  public int JJTMAIN = 12;
  public int JJTENIL = 13;
  public int JJTENTETES = 14;
  public int JJTENTETE = 15;
  public int JJTINIL = 16;
  public int JJTINSTRS = 17;
  public int JJTRETOUR = 18;
  public int JJTECRIRE = 19;
  public int JJTECRIRELN = 20;
  public int JJTSI = 21;
  public int JJTTANTQUE = 22;
  public int JJTAFFECTATION = 23;
  public int JJTSOMME = 24;
  public int JJTINCREMENT = 25;
  public int JJTAPPELI = 26;
  public int JJTLISTEXP = 27;
  public int JJTEXNIL = 28;
  public int JJTNOT = 29;
  public int JJTNEG = 30;
  public int JJTET = 31;
  public int JJTOU = 32;
  public int JJTEQ = 33;
  public int JJTSUP = 34;
  public int JJTADD = 35;
  public int JJTSUB = 36;
  public int JJTMUL = 37;
  public int JJTDIV = 38;
  public int JJTLONGEUR = 39;
  public int JJTVRAI = 40;
  public int JJTFAUX = 41;
  public int JJTEXP = 42;
  public int JJTAPPELE = 43;
  public int JJTTAB = 44;
  public int JJTRIEN = 45;
  public int JJTENTIER = 46;
  public int JJTBOOLEEN = 47;
  public int JJTNBRE = 48;
  public int JJTCHAINE = 49;


  public String[] jjtNodeName = {
    "root",
    "classe",
    "ident",
    "void",
    "vnil",
    "decls",
    "cst",
    "methode",
    "vars",
    "tableau",
    "var",
    "omega",
    "main",
    "enil",
    "entetes",
    "entete",
    "inil",
    "instrs",
    "retour",
    "ecrire",
    "ecrireln",
    "si",
    "tantque",
    "affectation",
    "somme",
    "increment",
    "appelI",
    "listexp",
    "exnil",
    "not",
    "neg",
    "et",
    "ou",
    "eq",
    "sup",
    "add",
    "sub",
    "mul",
    "div",
    "longeur",
    "vrai",
    "faux",
    "exp",
    "appelE",
    "tab",
    "rien",
    "entier",
    "booleen",
    "nbre",
    "chaine",
  };
}
/* JavaCC - OriginalChecksum=f82dda863a19a36a7b2cfb95427d61ca (do not edit this line) */
