/* Generated By:JavaCC: Do not edit this line. MiniJajaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJajaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEYWORD = 1;
  /** RegularExpression Id. */
  int INDENTIFIER = 2;
  /** RegularExpression Id. */
  int ASSIGN_OPERATOR = 3;
  /** RegularExpression Id. */
  int ADD_OPERATOR = 4;
  /** RegularExpression Id. */
  int SUB_OPERATOR = 5;
  /** RegularExpression Id. */
  int MULTIPLY_OPERATOR = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int SEPARATOR = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"int\"",
    "<INDENTIFIER>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<NUMBER>",
    "\";\"",
  };

}
