/* Generated By:JavaCC: Do not edit this line. MiniJajaDefaultVisitor.java Version 7.0.13 */
package fr.m1comp5.Analyzer.mjj;

public class MiniJajaDefaultVisitor implements MiniJajaVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTroot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTclasse node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTident node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvnil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTdecls node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcst node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmethode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvars node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtableau node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTomega node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmain node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTenil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTentetes node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTentete node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTinil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTinstrs node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTretour node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTecrire node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTecrireln node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsi node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtantque node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTaffectation node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsomme node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTincrement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTappelI node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTlistexp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexnil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTneg node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTet node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTou node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTeq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsup node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTadd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsub node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmul node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTdiv node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTlongeur node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvrai node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfaux node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTappelE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtab node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTrien node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTentier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTbooleen node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnbre node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTchaine node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=6f5bcb737350ed2eb69ad4ae11134538 (do not edit this line) */
